name: Run Data.cy.js Twice Daily

on:
  schedule:
    - cron: '0 7 * * *'   # 7:00 AM UTC
    - cron: '0 15 * * *'  # 3:00 PM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Data.cy.js
        env:
          CYPRESS_APP_URL: ${{ secrets.CYPRESS_APP_URL }}
        run: npx cypress run --spec "cypress/e2e/Data.cy.js"